// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hotel": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Hotel"
                ],
                "summary": "Add a new hotel",
                "parameters": [
                    {
                        "description": "Hotel data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.AddHotelDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ReturnIdDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/hotel/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Hotel"
                ],
                "summary": "Get all hotels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.HotelDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/hotel/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Hotel"
                ],
                "summary": "Get a hotel by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.HotelDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Hotel"
                ],
                "summary": "Update hotel by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Hotel data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.UpdateHotelDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.SuccessDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Hotel"
                ],
                "summary": "Delete a hotel by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.SuccessDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/hotel/{id}/room": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Add a new room to a hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New room data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.AddRoomDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ReturnIdDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/hotel/{id}/room/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Get all rooms for a hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.RoomDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/hotel/{id}/room/free": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Get all free rooms for a hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.RoomDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/reservation/:id/cancel": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Reservation"
                ],
                "summary": "Cancel a user's reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Reservation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.SuccessDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/reservation/:id/status": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Reservation"
                ],
                "summary": "Update the status of a reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Reservation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reservation status data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.UpdateReservationStatusDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.SuccessDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/reservation/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservation"
                ],
                "summary": "Get all reservations for the authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ReservationDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/reservation/all/manager": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservation"
                ],
                "summary": "Get all reservations (this request for the manager)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ReservationDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/room/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Get a room by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.RoomDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Update a room in a hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Room data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.UpdateRoomDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.SuccessDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Delete a room from a hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.SuccessDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/room/{id}/reserve": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Reservation"
                ],
                "summary": "Create a reservation for a room in a hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reservation data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.CreateReservationDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ReturnIdDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/sign-in": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign in to account",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.SignInRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.SignInResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/sign-up": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign up into account",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.SignUpRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ReturnIdDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.ErrorDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hotel-booking-app_internal_handler_dto.AddHotelDTO": {
            "type": "object",
            "required": [
                "location",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.AddRoomDTO": {
            "type": "object",
            "properties": {
                "max_occupancy": {
                    "type": "integer"
                },
                "price_per_night": {
                    "type": "number"
                },
                "room_type": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.CreateReservationDTO": {
            "type": "object",
            "required": [
                "check_in_date",
                "check_out_date"
            ],
            "properties": {
                "check_in_date": {
                    "type": "string"
                },
                "check_out_date": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.ErrorDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.HotelDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.ReservationDTO": {
            "type": "object",
            "properties": {
                "check_in_date": {
                    "type": "string"
                },
                "check_out_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "payment_status": {
                    "type": "string"
                },
                "room": {
                    "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.RoomDTO"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.ReturnIdDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.RoomDTO": {
            "type": "object",
            "properties": {
                "hotel": {
                    "$ref": "#/definitions/hotel-booking-app_internal_handler_dto.HotelDTO"
                },
                "id": {
                    "type": "string"
                },
                "max_occupancy": {
                    "type": "integer"
                },
                "price_per_night": {
                    "type": "number"
                },
                "room_type": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.SignInRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.SignInResponseDTO": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.SignUpRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.SuccessDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.UpdateHotelDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.UpdateReservationStatusDTO": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "hotel-booking-app_internal_handler_dto.UpdateRoomDTO": {
            "type": "object",
            "properties": {
                "max_occupancy": {
                    "type": "integer"
                },
                "price_per_night": {
                    "type": "number"
                },
                "room_type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Backend API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
